# Generated by Django 4.1.7 on 2023-04-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.JSONField()),
                ('training_file', models.FilePathField(null=True, path='C:\\Users\\BiokporSolomon\\OneDrive - Southend-on-Sea Borough Council\\Desktop\\Chat System\\aurora\\files', unique=True)),
                ('model_key', models.CharField(max_length=200, null=True, unique=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aurora_api.customer')),
            ],
        ),
    ]
