# Generated by Django 4.1.7 on 2023-04-28 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0003_alter_models_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='process',
        ),
    ]
