# Generated by Django 4.1.7 on 2023-04-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0004_remove_models_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='process',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
