# Generated by Django 4.1.7 on 2023-05-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0005_models_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='process',
        ),
        migrations.AddField(
            model_name='models',
            name='credentials',
            field=models.FileField(null=True, upload_to='C:\\Users\\BiokporSolomon\\OneDrive - Southend-on-Sea Borough Council\\Desktop\\Chat System\\aurora\\file/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='models',
            name='tokens',
            field=models.FileField(null=True, upload_to='C:\\Users\\BiokporSolomon\\OneDrive - Southend-on-Sea Borough Council\\Desktop\\Chat System\\aurora\\files/%Y/%m/%d/'),
        ),
    ]
