# Generated by Django 4.1.7 on 2023-05-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0006_remove_models_process_models_credentials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='credentials',
            field=models.FileField(null=True, upload_to='C:\\Users\\BiokporSolomon\\OneDrive - Southend-on-Sea Borough Council\\Desktop\\Chat System\\aurora\\credentials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='models',
            name='tokens',
            field=models.FileField(null=True, upload_to='C:\\Users\\BiokporSolomon\\OneDrive - Southend-on-Sea Borough Council\\Desktop\\Chat System\\aurora\\tokens/%Y/%m/%d/'),
        ),
    ]
