# Generated by Django 4.1.7 on 2023-05-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0008_alter_models_credentials_alter_models_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='credentials',
            field=models.FileField(null=True, upload_to='C:\\Users\\BiokporSolomon\\OneDrive - Southend-on-Sea Borough Council\\Desktop\\Chat System\\aurora'),
        ),
        migrations.AlterField(
            model_name='models',
            name='tokens',
            field=models.FileField(null=True, upload_to='C:\\Users\\BiokporSolomon\\OneDrive - Southend-on-Sea Borough Council\\Desktop\\Chat System\\aurora'),
        ),
    ]
