# Generated by Django 4.1.7 on 2023-05-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0012_remove_models_credentials_alter_models_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='origin',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
