# Generated by Django 4.1.7 on 2023-05-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0015_alter_models_smart_funnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='smart_funnel',
            field=models.CharField(default='False', max_length=5),
        ),
    ]
