# Generated by Django 4.1.7 on 2023-06-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0016_alter_models_smart_funnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='client_secret',
            field=models.JSONField(null=True),
        ),
    ]
