# Generated by Django 4.1.7 on 2023-06-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0020_appcredentials_remove_customer_client_secret_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='origin',
        ),
        migrations.AddField(
            model_name='customer',
            name='calendar_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='origin',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
