# Generated by Django 4.1.7 on 2023-06-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0021_remove_models_origin_customer_calendar_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='booking_questions',
            field=models.JSONField(null=True),
        ),
    ]
