# Generated by Django 4.1.7 on 2023-06-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0022_customer_booking_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mappings',
            field=models.JSONField(null=True),
        ),
    ]
