# Generated by Django 4.1.7 on 2023-06-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0024_treatments'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatments',
            name='notes',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
