# Generated by Django 4.1.7 on 2023-06-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0025_treatments_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatments',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='treatments',
            name='price',
        ),
        migrations.AddField(
            model_name='treatments',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='TreatmentSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aurora_api.treatments')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aurora_api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aurora_api.treatmentseller')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(through='aurora_api.TreatmentSeller', to='aurora_api.treatments'),
        ),
    ]
