# Generated by Django 4.1.7 on 2023-06-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0026_remove_treatments_notes_remove_treatments_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
