# Generated by Django 4.1.7 on 2023-06-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0027_price_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcredentials',
            name='platform',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
