# Generated by Django 4.1.7 on 2023-06-30 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0029_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('status', models.CharField(default='unpaid', max_length=50)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aurora_api.price')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aurora_api.customer')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aurora_api.treatments')),
            ],
        ),
    ]
