# Generated by Django 4.1.7 on 2023-06-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0030_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cost',
        ),
    ]
