# Generated by Django 4.1.7 on 2023-07-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0037_booking_sessionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_name',
            new_name='patient_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='phone',
            new_name='patient_phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.AddField(
            model_name='booking',
            name='patient_email',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='practise_email',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='practise_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='practise_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='summary',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='treatment',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
