# Generated by Django 4.1.7 on 2023-07-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0038_rename_user_name_booking_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='closing',
            field=models.JSONField(null=True),
        ),
    ]
