# Generated by Django 4.1.7 on 2023-07-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0039_customer_closing'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='treatment_init',
            field=models.JSONField(null=True),
        ),
    ]
