# Generated by Django 4.1.7 on 2023-08-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0040_customer_treatment_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatments',
            name='booking_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='treatments',
            name='calendar_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
