# Generated by Django 4.1.7 on 2023-08-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0041_treatments_booking_duration_treatments_calendar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_duration',
            field=models.IntegerField(default=15),
        ),
    ]
