# Generated by Django 4.1.7 on 2023-09-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0042_booking_booking_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('amount', models.IntegerField()),
                ('email', models.CharField(max_length=250)),
                ('dob', models.DateField()),
            ],
        ),
    ]
