# Generated by Django 4.1.7 on 2023-09-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0043_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='setting',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
