# Generated by Django 4.1.7 on 2023-09-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0044_booking_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatments',
            name='treatment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
