# Generated by Django 4.1.7 on 2023-09-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0046_alter_customer_booking_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='booking_questions',
            field=models.JSONField(null=True),
        ),
    ]
