# Generated by Django 4.1.7 on 2023-10-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0049_alter_customer_booking_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=250)),
                ('response', models.TextField(max_length=250)),
                ('rating', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
