# Generated by Django 4.1.7 on 2023-10-31 14:03

import aurora_api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0051_alter_models_training_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcredentials',
            name='google_secret',
            field=aurora_api.models.S3FileField(null=True, unique=True, upload_to='upload_to'),
        ),
    ]
