# Generated by Django 4.1.7 on 2023-11-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0052_alter_appcredentials_google_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='intent',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
