# Generated by Django 4.1.7 on 2024-01-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0055_ratelimitsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='rating',
        ),
        migrations.AddField(
            model_name='chat',
            name='chats',
            field=models.IntegerField(default=1),
        ),
    ]
