# Generated by Django 4.1.7 on 2024-01-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_api', '0057_chat_human_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='reason',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
