# Generated by Django 4.1.7 on 2023-06-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripeaccounts', '0002_stripeinfo_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeinfo',
            name='account_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
