# Generated by Django 4.1.7 on 2024-01-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripeaccounts', '0003_stripeinfo_account_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeInfo',
        ),
    ]
